geojson_pydantic/features.py
The Feature model now accepts MultiPoint as a valid geometry (before MultiPolygon was repeated twice and MultiPoint not included).
=> Include MultiPoint as valid geometry for Feature

geojson_pydantic/geometries.py, requirements.txt, setup.py, test/test_geometries.py
Hi,
Turned out getting rid of the `geojson` dependency wasn't that hard. Most of it was already covered by the models that was created. 
I hope you like it.
Fixes #2.
=> chore: Remove geojson dependency

CONTRIBUTING.md, README.md
Hi,
I'm not quite sure on if this is the preferred way for you to run/install tox, and/or if you even want the `CONTRIBUTING.md` file to be included.
Maybe `tox` should be included as a dev dependency somehow.
Personally I've switched 100% to `poetry`. I have not tested it with `tox` yet. I use GitHub actions matrix builds for testing different OSes and python versions. See https://github.com/hawkaa/pygeojson .
Let me know what you think!
=> docs: Add documentation on how to run tests

.github/workflows/ci.yml, .pre-commit-config.yaml, CHANGELOG.md, geojson_pydantic/__init__.py, setup.cfg, setup.py, tox.ini
closes #24 
This PR does:
- update pre-commit config to run on any python version
- add python 3.9 in the CI 
- move config lint config from tox.ini to setup.cfg
- fix #24
=> Fix version number

CHANGELOG.md, README.md, geojson_pydantic/__init__.py, geojson_pydantic/geometries.py
=> Top level export

CHANGELOG.md, geojson_pydantic/features.py, geojson_pydantic/geometries.py, geojson_pydantic/types.py
closes #32, closes #19 
This PR does:
- rename `utils.py` to `types.py` **breaking** (I've looked in GitHub and no one is importing `geojson_pydantic.utils` (which only had `types` variables)
- move `Coordinate` type to `types.py` and rename it `Position)  **breaking**
- use absolute imports
cc @geospatial-jeff @drewbo
=> rename utils.py and move position variable

geojson_pydantic/geometries.py, test/test_features.py, test/test_geometries.py
The main goal of this PR was to improve test coverage.  Two cases were not covered:
- Calling `parse_geometry_obj` on an object with no `type` member.
- Creating a geometry from an object implementing the `__geo_interface__` protocol.
Testing the first case revealed a bug that is also fixed in this PR.
Run pytest!
=> improve test coverage, fix a bug

geojson_pydantic/geometries.py, geojson_pydantic/types.py
Use `pydantic.conlist` to type coordinate arrays because it allows specifying `min_items`.  The arguments to `conlist` appear in the auto-generated JSON schema which makes it a better representation of the geojson spec.  Only `LineString` implemented this before this change, now all the geometry types have length constraints on their coordinate arrays.
I noticed this while using `hypothesis-jsonschema` to autogenerate fake data against the JSON schema created by `geojson-pydantic`.  Hypothesis would generate coordinates arrays with invalid number of members (ex. a linear ring with one coordinate).
Because the coordinates members for different geometries build off of eachother I decided to define types for each coordinates type in `types.py` and reference those types in the pydantic …
=> use pydantic.conlist to define coordinate arrays

geojson_pydantic/features.py, test/test_features.py
According to the specs, the geometry attribute of a geojson Feature can be set to `null`. See https://datatracker.ietf.org/doc/html/rfc7946#section-3.2 . But the geometry in the Feature definition in geosjon-pydantic is required.
Wrap the geometry value with an `Optional[]` tag in the feature definition.
I added a test for this case, but I am not sure if the test is sufficient the way I wrote it. I am not very familiar with pydantic.
Fixes https://github.com/developmentseed/geojson-pydantic/issues/46
I came across this problem while using stac-fastapi, which uses stac-pydantic, which uses this library. The downstream issues are the following:
https://github.com/stac-utils/stac-pydantic/issues/107
https://github.com/stac-utils/stac-fastapi/issues/350
=> make feature geometry optional

.pre-commit-config.yaml, CHANGELOG.md, geojson_pydantic/features.py, setup.py, tox.ini
This PR addresses #55 by setting the default value of `bbox` and `geometry` on features to `None`
=> Allow None to be passed for geoms and bboxes on features

CHANGELOG.md
Just some improvement to your changelog file
The "Keep a Changelog" format usually has the compare links to directly see all changes made within a version jump.
For future releases the first of the unreleased link needs to be adjusted and one for the new release added.
- [Default](?expand=1&template=default.md)
- [Version Release](?expand=1&template=version_release.md)
- _Alternatively delete and start empty_
=> Fix changelog compare links

geojson_pydantic/features.py, geojson_pydantic/geometries.py, tests/test_features.py
The `bbox` key should not be in a geojson object if the bbox is `None`. If the key is present, the value is expected to be a tuple, see https://datatracker.ietf.org/doc/html/rfc7946#section-5
In ths PR, I also moved the `__geo_interface__` into a mixin to reduce code duplication.
There is one design question where I was not sure what is the best:
The bbox check could  be added into the `dict()` method directly. Depending on whether the expected output of `dict` is a valid geojson like dictionary, or the "full" data from the pydantic model. Please advise, I am happy to change that if its considered better to put it into the `dict` method.
=> Fix geo_interface output when bbox is None

CHANGELOG.md, geojson_pydantic/geometries.py, geojson_pydantic/types.py, tests/test_geometries.py
I believe this to be more correct based on the spec.
Updated all the tests due to the automatic conversion to float making `(1, 2) != (1.0, 2.0)`. 
Tweaked `assert_wkt_equivalence` so it doesn't fail when using a number such as `1.01`. 
Discussion: developmentseed/geojson-pydantic#82
=> Remove NumType and use float throughout.

CHANGELOG.md, geojson_pydantic/geometries.py, tests/test_geometries.py
- Make the `_wkt_type` function work when the class is inherited from.
- Switched the `_wkt_type` function to use the `type`. Since a "type" MUST exist in the spec, and it cannot be modified. It will always match the WKT type unlike the class name.
- Tests still run properly. And now this works:
```python
from geojson_pydantic import Point
class PointType(Point):
...
print(PointType(coordinates=[123, 123]).wkt)
```
- Fixes: developmentseed/geojson-pydantic#78
=> Switch WKT to use type over class name.

geojson_pydantic/features.py, geojson_pydantic/geometries.py, tests/test_features.py, tests/test_geometries.py
Per further discussion in: https://github.com/developmentseed/geojson-pydantic/discussions/66#discussioncomment-3294233
Can use `pydantic.Json[Polygon]` in a model to load from string.
=> Remove validate function to load from a string.

.pre-commit-config.yaml, CHANGELOG.md, geojson_pydantic/features.py, geojson_pydantic/geometries.py, geojson_pydantic/types.py, pyproject.toml, tests/test_features.py, tests/test_geometries.py
- Adjusted typing throughout the package to be more complete and accurate.
- Updated pre-commit to run mypy on the whole package vs individual files.
- Clean up defaults so `type` isn't treaded as required and `Optional` all have default `None` and aren't considered required either. 
- Tweaked mypy to use pydantic plugin and have slightly stricter rules.
- Tweaked types until mypy no longer threw errors.
- Tweaked types until pyright was no longer throwing errors in the module. 
- Validated typing in the tests so there were no major complaints. 
Hopefully this is reasonable. It does touch a bunch of lines but I tried to avoid anything other than types.  
I would have preferred to not do the `if TYPE_CHECKING` in `types.py` but the alternative was `Annotated` and I found a bug in pydantic …
=> Cleanup Types to make Mypy and Pyright happier.

.github/workflows/ci.yml, CHANGELOG.md, geojson_pydantic/features.py, geojson_pydantic/geometries.py, pyproject.toml, tests/test_features.py, tests/test_geometries.py
=> Enforce type geometry properties

geojson_pydantic/geometries.py, geojson_pydantic/types.py, tests/test_geometries.py
- Fix #89 and allow empty arrays. 
- Removed `conlist` from the types which are not constrained. `LineString` and `LinearRing` still have min items. 
- Tweaked existing tests, and added some new ones. 
- Issue: #89 
- Alternative to PR: #99
=> Allow empty coordinate arrays

geojson_pydantic/geometries.py
- Add discriminator to `Geometry` to check less types, and simplify errors.
- `Annotated` it.
- Existing tests still work. 
- Related: #93 
Unfortunately this PR does not do the second part, so I didn't way to say it fixes the issue entirely. 
```python
class Feature(GenericModel, Generic[Geom, Props]):
...
geometry: Annotated[Union[Geom, None], Field(..., discriminator="type")]
```
Causes errors in the tests when the generic is overridden with a single `Geometry` type. It results in `TypeError: 'discriminator' can only be used with 'Union' type with more than one variant`
=> Add Geometry discriminator

geojson_pydantic/geometries.py, tests/test_geometries.py
- Add a `has_z` property to Geometries to simplify WKT and facilitate additional capabilities such as `force_2d` and `force_3d` in the future. 
- Added helper functions to determine if any of the coordinates have a Z value
- Used those functions for the property each geometry type
- Removed individual `_wkt_inset` functions since we can reference `.has_z` 
- It was already being tested on some level some via WKT tests.
- Added tests dedicated to the function, including weird mixed dimensionality cases not covered in WKT
- Related #98
- Related #102
=> Add has_z function to Geometries.

geojson_pydantic/features.py, geojson_pydantic/geo_interface.py, geojson_pydantic/geometries.py
- Refactored the code to use a single function for all `__geo_interface__` methods. Because the models represent geojson already returning themselves as a dict is all that is necessary. This implementation aligns with what other libraries are doing as well as the discussion in #96. The original gist pre-dates the current geojson spec and has some slight inconsistencies, but the intent is to match geojson.
- Added a standard mixin for `__geo_interface__` to use on the models. 
- Use `self.dict()` for the response.
- No tests were changed and they all still pass. 
- The primary test for this is probably a bit implicit inside the WKT tests. Since shapely reads the `__geo_interface__` and then produces the same WKT as our WKT functions we know it is producing usable data in …
=> Refactor geo_interface to use a standardized mixin.

geojson_pydantic/geometries.py
- Remove the `LinearRingGeom` class. It doesn't correspond with an actual GeoJSON type and it is not used in any other part of the code. It also had no tests or anything related to it. 
I think this probably originated from the desire to have the validation on the coordinates and not inside Polygon, but it was not actually being used. I have been experimenting with a class for `LinearRingCoords` that may end up similar with the validation is inside the type and not on Polygon. But if I can get it working that will be a different PR. 
- Remove the LinearRingGeom class.
- This code wasn't actually used anywhere, and didn't have any related tests. 
- I had originally included this in an earlier PR that got split up (#85), but I didn't remember it was still there until recently.
=> Remove unused LinearRingGeom class.

CHANGELOG.md, geojson_pydantic/geometries.py, tests/test_features.py
- Add BBox to Geometries.
- Add optional bbox to `_GeometryBase` and `GeometryCollection`
- Only one minor tweak to a test. Don't think anything new is needed for the optional field.
- n/a
I was looking over some CQL2 stuff and got confused when I saw an optional BBox on their Geometries, but technically that is correct. 
> A GeoJSON object MAY have a member named "bbox" to include information on the coordinate range for its Geometries, Features, or FeatureCollections.
=> Add BBox to Geometries.

geojson_pydantic/geometries.py, tests/test_geometries.py
- Addressing mixed dimensionality edge case on WKT functions.
- Add capability to `force_z` in wkt functions.
- Use `has_z` to determine when to force the inclusion of z.
- Adjust signatures to work together. 
- All the current tests still work. 
- #102 
---
It was a bit weirder than I wanted to only run `has_z` once at the top level. I iterated way too many times on figuring out the best way to set the wkt coordinate functions at the class level. I think I am finally OK with how its set up. 
- ~~Move helper functions to `wkt.py`?~~
=> Address mixed dimensionality in wkt

CHANGELOG.md, geojson_pydantic/geometries.py, tests/test_features.py, tests/test_geometries.py
Closes #110.
- Added support for nested GeometryCollection (with warnings)
- Tweaked some tests to not throw the warnings. 
- Changed the type to a Union, and updated types / tests to match. 
- Updated tests. 
- #110
=> Add support for nested GeometryCollection with warnings.

README.md
Quick fix for anaconda badge
before:
after:
=> Fix anaconda badge

geojson_pydantic/features.py, geojson_pydantic/geometries.py, geojson_pydantic/types.py, tests/test_features.py
- Add consistent bbox validation across the board.
- Add more specific validation errors to bbox. 
- Create a generic bbox validation function, and re-use it everywhere.
- Existing tests, plus one additional.
- #118 reminded me of what I had done, so I finished cleaning it up.
I tried a lot of different ways to accomplish this with mixins and such, but none of it worked out for Pydantic 1.x. Mostly had issues with differences between `GenericModel` and `BaseModel`. Looks like there are probably better ways to do some of this for Pydantic 2.x, but haven't dug into it yet. Just wanted to push this so I wouldn't forget again.
=> Additional bbox validation.

.pre-commit-config.yaml, CHANGELOG.md, pyproject.toml
```
tests/test_package.py:1: in <module>
import geojson_pydantic
geojson_pydantic/__init__.py:3: in <module>
from .features import Feature, FeatureCollection  # noqa
geojson_pydantic/features.py:6: in <module>
from pydantic.generics import GenericModel
E   ImportError: cannot import name 'GenericModel' from 'pydantic.generics' (/Users/vincentsarago/Dev/venv/py39/lib/python3.9/site-packages/pydantic/generics.py)
```
we will update the pydantic version in `1.0`
=> limit pydantic requirement to 1.0

geojson_pydantic/features.py, geojson_pydantic/geometries.py, geojson_pydantic/types.py, tests/test_features.py, tests/test_geometries.py
Pointed at `pydantic2.0` branch for now since it is branched from there. It is meant to be pointed to `develop` after that branch is merged. Can switch it from Draft to Ready whenever. 
- Finish fixing #93 
- Added `GeometryCollection` case to `parse_geometry_obj`
- By adding `GeometryCollection` into the `Geometry` type we no longer have the issue with a second discriminator. 
- All the existing tests continue to pass.
- Added a test to check the the example from #93 results in a single `ValidationError`. 
- Added a test for parsing a `GeometryCollection` in `parse_geometry_obj`
- Fixes #93 the rest of the way. 
- This was probably mostly enabled by #110 / #111 but the 2.0 update may have helped as well.
=> Tweak Geometry to include GeometryCollection. Fixes: #93

CHANGELOG.md, geojson_pydantic/features.py, tests/test_features.py
Update the generic `FeatureCollection` model to depends only on a generic `Feature` model.
```python
FeatureCollection[Geometry, Properties]
FeatureCollection[Feature[Geometry, Properties]]
```
Related to issue [#134](https://github.com/developmentseed/geojson-pydantic/issues/134)
=> Feature collection generic

CHANGELOG.md, geojson_pydantic/geometries.py, tests/test_geometries.py
- Attempt to fix issues with WKT and its tests.
- Adjusted `MultiPoint` to include parentheses around each set of Point coordinates.
- Adjusted tests because we can no longer rely on a consistent output from Shapely / Geos.
- Attempted to address all the cases in a new test.
- Fixes #139 Though some of the fix is just avoiding the issues in Shapely / Geos not changing anything for us. 
The `NaN` behavior in Geos is weird, as it is not valid WKT, but I understand what they are doing rather than assuming `0.0` as the Z value. It doesn't look entirely resolved on the Shapely side either, so I don't think there is much to do for now. Unless we just stop using the `force_z` stuff, and let stuff like `"MULTIPOINT Z ((0.0 0.0), (1.0 1.0 1.0))"` be output. It is parseable by `shapely.from_wkt` at …
=> Tweak WKT generation and tests.

CHANGELOG.md, geojson_pydantic/base.py, tests/test_features.py
Fixes #147.
```
>>> f.model_dump(include={"geometry"})
{'geometry': {'bbox': None, 'type': 'Polygon', 'coordinates': [[(-123.07498674, 44.04971882), (-123.07554223, 44.06248623), (-123.0625126, 44.06278031), (-123.06195992, 44.05001283), (-123.07498674, 44.04971882)]]}}
>>> f.model_dump(exclude={"geometry"})
{'bbox': None, 'type': 'Feature', 'properties': {'a': 1, 'b': 2, 'c': 3}, 'id': None}
>>> f.model_dump_json()
'{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-123.07498674,44.04971882],[-123.07554223,44.06248623],[-123.0625126,44.06278031],[-123.06195992,44.05001283],[-123.07498674,44.04971882]]]},"properties":{"a":1,"b":2,"c":3}}'
>>> f.model_dump_json(include={"geometry"})
'{"geometry":{"type":"Polygon","coordinates":[[[-123.07498674,44.04971882],[-123.07554223,44.06 …
```
=> Adjust model serializer.

geojson_pydantic/base.py, tests/test_geometries.py
- This is a temporary workaround until https://github.com/tiangolo/fastapi/discussions/10661 is answered in a better way. I am just making this available here in case someone else would like to use it. I can finalise it better(changelog and such) if this is something that wants to be merged into main.
- Changing the typehinting according to workaround mention [here](https://github.com/tiangolo/fastapi/discussions/10661#discussioncomment-7631104) to get the model to show up in fast api swagger docs.
- See https://github.com/developmentseed/geojson-pydantic/issues/150 for a simple case.
- https://github.com/developmentseed/geojson-pydantic/issues/150
=> Workaround for #150 FastAPI shows no attributes for models.

.pre-commit-config.yaml, geojson_pydantic/features.py, geojson_pydantic/geometries.py, geojson_pydantic/types.py, pyproject.toml, tests/test_features.py, tests/test_geometries.py
This change incorporates the use of the Pydantic v1 namespace which was introduced in Pydantic 1.10.17 and all 2.x versions. This allows the use of Pydantic v1 while also supporting either Pydantic >=1.10.17,<3. The goal being to allow users of this package a planned upgrade path to Pydantic 2.x instead of an abrupt switch.
See https://github.com/developmentseed/geojson-pydantic/issues/166 for more on this issue
- Changed the Pydantic dependency to >1.10.18 (latest) and <3 (all 2.x versions)
- Changing all Pydantic import statements to use the `v1` namespace (e.g. `from pydantic.v1 import ...`)
- Verified all existing unit tests pass
- Verified existing functionality works as expected on private services
See the Pydantic migration guide which was updated to reference the new v1 namespace …
=> Switch to Pydantic v1 namespace and allow Pydantic v1 or v2

.github/workflows/ci.yml, .pre-commit-config.yaml, CHANGELOG.md, geojson_pydantic/base.py, geojson_pydantic/geometries.py, pyproject.toml, tests/test_features.py, tests/test_geometries.py
This PR does:
- drop python 3.8 support 
- add python 3.13 
- ~~add python 3.14 in CI~~
- replace black formatting by ruff-format
=> update python version support and switch to ruff-format

CHANGELOG.md, geojson_pydantic/features.py, geojson_pydantic/geometries.py, tests/test_features.py, tests/test_geometries.py
=> remove conflicting iter len getitem methods
